### ISSUE TITLE
CourgetteOptions ignores Cucumber tags

### ISSUE THREAD

**Issue by HesterLyonsMaru** [prashant-ramcharan/courgette-jvm#112]
I've used Courgette successfully for weeks for a project that was getting bigger and bigger. I finally decided to split it into tests and page definitions, with the test project having a dependency on the page objects. The setup builds and runs individual features fine through the IDE, but when I use the RunTests class which is set up to run through Courgette, it ignores my tags and runs all scenarios (using IntelliJ with a Gradle build, tests run through JUnit).

I can provide code if needed but wondered if anyone had come across Courgette ignoring the Cucumber tags at all.

**Comment by HesterLyonsMaru** [comment]
[compositeproject.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/3141687/compositeproject.zip)

The attached is a minimum setup of the problem. There are two modules in this zip, the main one being frameworktests, the dependency being pagedefinitions. There are two features which are tagged @tutorial (a feature that does a visit to Google) and @notrun (a feature without definitions). RunTests.java  is set up to only use cucumber tag @tutorial. 

When the tests are run both features run. 

I have included the courgette report which does not report on the feature tagged @tutorial, but does report on the failed test in feature @notrun.

**Comment by prashant-ramcharan** [comment]
Your Cucumber feature files are within sub directories inside the resources directory. 

Your Courgette runner needs to specify the sub directory for Cucumber to load the correct runtime options and for Courgette to build the resource path for each scenario otherwise all features would get run matching the scenario line number.

Using your provided project, simply update the features path in your Courgette runner with this:

````java
 features = "src/test/resources/features",
````

**Comment by HesterLyonsMaru** [comment]
Thank you, I don't know how I missed this. It's now working absolutely fine, of course. Much appreciated.
