### ISSUE TITLE
Can cucumber scenario run in parallel on 2 different VM  

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#131]
Hi @prashant-ramcharan I have a requirement where i have to integrate our framework with AWS to run cucumber scenarios in parallel on available AWS slave machines.

My question to you is : 

Lets say :
 
1) I have 10 Scenarios written in 1 feature file
2) CourgetteRunner has Thread count = 3 and runLevel = CourgetteRunLevel.SCENARIO

When i trigger Jenkins job i have 1 AWS master slave integrated with 3 AWS Slave machines 

in this case i want 3 scenarios to run parallel in each AWS Salve  machines (3 slave machines) and remaining 1 will run after any 1 AWS slave machine available.

Will it take care by your library ? 

When i run it locally i see it opens 3 browser at the same time and run scenario in parallel but when it comes to running on cloud thru jenkins WILL IT ALSO TAKEN CARE BY "courgette-jvm" ?

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
Short answer: No, this is not supported.

You'd have to define your own run / test distribution strategy in your CI tool.

**Comment by LearningPur** [comment]
@prashant-ramcharan I know you have closed this and i don't wanna re open it.

Like you mentioned in your reply above would you please mind to give an idea how to make it work with CI using your library ? You mentioned "You'd have to define your own run / test distribution strategy in your CI tool." regarding that if you can please share some idea. I am sure there will be lot more guys who might also looking for an answer on this as nowadays without CI there is no success in real project. 

Thanks
Vinit

**Comment by prashant-ramcharan** [comment]
You should aim to **Dockerise** your tests. This ensures that tests are portable and are independent of platform / environment infrastructure.

So if you have 3 build agents each agent could run a subset of tests. For example,

Build Agent A: run tests tagged with '@login' using the built docker test image.
Build Agent B: run tests tagged with '@register' using the built docker test image.
Build Agent C: run tests tagged with '@customer' using the built docker test image.

You should design your test framework to be configurable so that your CI tool can dynamically configure the tests (_i.e. filter tests by tags / provide system properties / JVM configuration etc._)

Courgette allows you to configure the tests at runtime so this would work well with CI + Docker containerisation.

**Comment by LearningPur** [comment]
Thank you so much @prashant-ramcharan  as always replying in regular manner without forget. 

We have **_Sauce Lab Cloud_** to run our test in parallel is it possible if i follow an approach what you have mentioned in your comment above will help ?

Thanks
Vinit
