### ISSUE TITLE
Extent report with latest version not creating html report

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#155]
Hi @prashant-ramcharan , Since there is a bug to attach screenshot in extent report using base64 i am trying to upgrade extent cucumber adapter version with latest which is 1.0.10 but i noticed with version 1.0.10 extent html report is not getting created but with 1.0.7 it does create.

To me just by upgrading version it should not stop creating html report. 

I will recap an base64 issue that i am taking about is when base64 String size will be bigger execution will take forever and will not create extent report so i though of trying with latest version out there which is 1.0.10

Here are both screenshot where you can see 1 has report.html with version 1.0.7 and other doesn't have report.html when upgrading version to 1.0.10

![Screen Shot 2020-01-30 at 11 46 02 AM](https://user-images.githubusercontent.com/57417403/73476206-6f7e8600-4357-11ea-8333-94d9c3206d34.png)

![Screen Shot 2020-01-30 at 11 49 41 AM](https://user-images.githubusercontent.com/57417403/73476178-64c3f100-4357-11ea-8329-7cd1a3448080.png)

There is an issue i reported "How to add custom log along with screenshot in extent report #151" regarding base64 is still happening i thought it worked but i noticed as soon as i remove the saved image screenshot in extentreport coming as broken. 

If you want to try to replicate an issue please try to take an screenshot of full page and convert it using base64 and see if that attach to extentreport. It will fail i am sure as i spent 2 days and still trying to figure out an issue.

**Comment by prashant-ramcharan** [comment]
Courgette uses version **1.0.7** so by updating your local dependancy to 1.0.10 will not guarantee that Courgette would work with the newer API.

Courgette uses the Community version of Extent Reports so embedding base64 screenshots is **not included** in this version. Embedding base64 screenshots is only allowed in the Pro version.

The Community version only allows for images to be referenced by a `href`. This is why Courgette first saves the image then references it from the report.

Embedding base64 images was never support by Courgette because it not include in the Extent Reports Community addition.

#151 was just a sample of how one could embed a base64 image using the log functionality however this is not a supported way of using it and it's not natively supported by Courgette due to the limitations noted above.

https://extentreports.com/docs/versions/3/java/

<img width="874" alt="Screenshot 2020-01-30 at 19 40 53" src="https://user-images.githubusercontent.com/2563149/73484825-ec325400-4399-11ea-8a31-cddfd0f7c2a9.png">

**Comment by LearningPur** [comment]
Thank you so much for your detail finding.

Reading your comment above did you mean to say currently even "Courgette html report" is not even supported base64 screenshot ? Sorry if i mis understood your comment but i am seeing base64 screenshot works for Courgette html report. What it does is it saves the image, convert it to base64 and from cucumber.json it uses the base64 string to upload it to Courgette html report.

Is it possible for extent report ? base64 string is saving it to cucumber.json and because of that it also display in cucumber and Courgette html report both but somehow it does NOT for extent report.

**Comment by prashant-ramcharan** [comment]
> Reading your comment above did you mean to say currently even "Courgette html report" is not supported base64 screenshot 

No, I did not say that Courgette html report cannot embed base64 images. There is not related to Courgette or Cucumber html reports. As previously mentioned, the limitation is in Extent Reports Community version which does not support embedding base64 images.

> Is it possible for extent report ? base64 string is saving it to cucumber.json and because of that it also display in cucumber and Courgette html report both but somehow it does NOT for extent report.

No, Courgette cannot use Extent Reports Community version to embed base64 because this feature is only available in the **Pro version**.

_Please remember, this is simply a Courgette plugin. The limitations in external libraries such as Extent Reports Community version is not something that I can fix or work around._

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur - Please use image/png instead of base64 images as this would be the only way to include images in Extent Reports using the Community version.

**Comment by LearningPur** [comment]
@prashant-ramcharan  If you really don't mind can you please jump on this thread that i have started creating an extent report issue. 

https://github.com/extent-framework/extentreports-java/issues/120

That guy is saying it's not an extent report issue, something that prevent from your library (Courgette ) to attach base64 screenshot. 

I really appreciate if you can please input your comment at the end so they understand this is not an issue form Courgette and issue from extent report.

**Comment by prashant-ramcharan** [comment]
Please note: Embedding base64 images is **not supported** in the Courgette / Extent Report integration. 

@LearningPur I suggest you use Extent Reports directly if you wish to embed base64 images.

**Comment by LearningPur** [comment]
@prashant-ramcharan  I am really sorry and apologies if I took your name as you mentioned it's an extent report issue which is from your side it's not. 

My concern here is if base64 string when it is small it does attach to extent report then why it does not when it lil bit bigger

**Comment by LearningPur** [comment]
@prashant-ramcharan  Since your busiest guy not sure if you have some time but i have created sample project for the extent report dev guy to look into it that i am sharing same to you would you please mind to take a look at it

[extentReportIssue.zip](https://github.com/prashant-ramcharan/courgette-jvm/files/4172668/extentReportIssue.zip)

Please do give it a try to run sample project using runner.java class and go to below folder

"Target/HtmlReport/courgette-extentreports/index.html" : This is an extent report when you open it you won't find screenshot attached to it.
"Target/HtmlReport/courgette-report/index.html" : This html report you will find screenshot (base64) attached

if you comment out below 2 lines

// byte[] htmlImage = ("<img class="col-lg-12" src="data:image/png;base64," + base64Image + "">").getBytes();
// getScenario.embed(htmlImage, "text/html");

and uncomment below line

getScenario.write("<img src=data:image/png;base64," + base64Image + ">");

you will notice execution will take forever that is strange, is it still due to extent report community version ?

**Comment by prashant-ramcharan** [comment]
Follow: https://github.com/prashant-ramcharan/courgette-jvm/issues/157
