### ISSUE TITLE
Unable to take the latest version supporting only 2.3.1

### ISSUE THREAD

**Issue by Sunitha-Sharma** [prashant-ramcharan/courgette-jvm#166]
Hi Prashant,
When I'm trying to use any of the latest version in my gradle project. It is removing ide modules which is present. Same is not happening, if I'm using the old version.
Is it possible for parallel execution to happen if my using 2.3.1 version by removing rest of the cucumber versions.. because when I compared your latest version with this 2.3.1 I found cucumber option java file which is not present. 
If it is still possible to execute feature files in parallel. Can you share me steps to execute it.. or can you help me to resolve this issue.

Gradle version:1.0.87

**Comment by prashant-ramcharan** [comment]
Hello,

Courgette version `2.3.1` uses Cucumber version 2+.

Because the newer Courgette versions uses a newer version of  Cucumber this would cause some package names (i.e. Cucumber options) to be moved / changed. You'd have to update your project to address this.

The latest version of Courgette uses Cucumber v5.

**Comment by Sunitha-Sharma** [comment]
Oh okay thanks..
