### ISSUE TITLE
Is Courgette-jvm capable running mobile automation test in parallel using Appium ?

### ISSUE THREAD

**Issue by LearningPur** [prashant-ramcharan/courgette-jvm#192]
Hi @prashant-ramcharan Just out of the curiosity is your library capable of running mobile automation test (Android, iOS) in parallel using Appium ?

In our company we have framework implemented for Mobile apps using Appium and Selenium and currently we are running cucumber test on device one after another. 

We are planning to run our mobile apps automation test in parallel and hunting for best library out there. I came across this library which looks demanding but before we go ahead and start integrating in our framework we wanna make sure if it is capable of running mobile appium test in parallel.

Thanks

**Comment by prashant-ramcharan** [comment]
Hi @LearningPur ,

If the project uses Cucumber then yes, Courgette will run those features / scenarios in parallel.

Having said that, you have to configure your test framework to target the correct device before each feature / scenario. This is not something Courgette will do for you.

As you can only run a single test on a device at a time, you'd need to have multiple devices / simulators to support parallel device testing. The important bit is to keep track of the active sessions / devices so that you can allocate each test to a free device / simulator. http://appium.io/docs/en/advanced-concepts/parallel-tests/

With Courgette, it's simple enough to start the Appium server once using [Courgette callbacks](https://github.com/prashant-ramcharan/courgette-jvm#junit-callbacks) and then each scenario can run in parallel provided that you have enough simulators / devices to run on.

**Comment by LearningPur** [comment]
Thank you so much for your valuable time @prashant-ramcharan and replying. 

Currently we have running our Appium Cucumber based test on Browser Stack cloud simultaneously one after another BUT we have requirement/plan to convert that into parallel execution and that's how i came to know your awesome library that i already used in one of my Web automation framework and that works like a charm. 

When you will have some time can you please create sample project like how you have done for Web. 

That sample project will help to get an idea how we can use Courgette library to run Appium cucumber based test in parallel multiple Android and iOS devices. 

Thanks Much

**Comment by prashant-ramcharan** [comment]
@LearningPur will try adding a project when I get a chance.

**Comment by mateiQA** [comment]
any updates here?

**Comment by prashant-ramcharan** [comment]
https://github.com/prashant-ramcharan/courgette-jvm-appium-ios
