### ISSUE TITLE
Feature request - dynamic expression for rerunFailedScenarios

### ISSUE THREAD

**Issue by amitmindstix** [prashant-ramcharan/courgette-jvm#20]
Is there a possible way to use conditional rerun of failed scenarios - e.g. only rerun when the pass % is below a threshold - say 80%?
Please suggest if there are possible ways to achieve this.

**Comment by prashant-ramcharan** [comment]
Each rerun is triggered in the same thread at the **point of failure** so knowing 80% of failures without having run all scenarios first would not be possible, as it currently stands.

My suggestion would be defer the rerun of failed scenarios once all scenarios are executed.

1. Set rerunFailedScenarios to 'false' in the runner.
2. In you CI tool, determine whether to rerun the failed scenarios based on your failure threshold.
3. Execute the rerun file (using Cucumber) which is located in the target directory 

(_Note. Courgette-JVM produces a single rerun text file listing all failed scenarios._)

**Comment by prashant-ramcharan** [comment]
I can upgrade Courgette-JVM to defer the rerun of failed scenarios once all test are complete. Based on a failure threshold, the tests would rerun.

Will look into adding this to the next release.

**Comment by amitmindstix** [comment]
Awesome! Thanks!

**Comment by prashant-ramcharan** [comment]
On further investigation, I've decided that this feature will not work effectively. Because each feature/scenario is delegated its own thread at the start, that thread is responsible for running, re-running and reporting.

If we defer the re-run until all threads are complete, then the re-run would happen synchronously and we would then have to go back and update the multi-threaded reports -- this is messy. 

The reason why it currently works well is because each thread takes responsibility for it own work (run -> re-run -> report)

As previously mentioned, set rerunFailedScenarios to false and run the failed scenarios using the 'courgette-rerun.txt'.
