### ISSUE TITLE
[Slack]- Test Run Summary card can show more details

### ISSUE THREAD

**Issue by Vishnuvenu89** [prashant-ramcharan/courgette-jvm#310]
currently test run summary shows below data

We can further customize this by adding below options

> Option to show the name of the test suite - Regression/Sanity/Prod Testing  - can be set via CourgetteOptions
> Also option to send Report(Extent/Allure) as link to slack 
![image](https://user-images.githubusercontent.com/88667605/151652576-5954e071-d398-4aae-b430-eba3cf2ff520.png)

**Comment by mateiQA** [comment]
While we are on this subject, maybe allow a setter method for Session ID so that we can chain multiple runners together based on it? For now, I assume, every runner will create a new session id and if you run 2 runners in the same test run via gradle/maven you will get 2 different test summaries. If we could chain them and create a session id from outside (gradle or mvn build scripts) and pass it to the runner classes we could chain multiple test runners as part of the same 'run'. Concrete example: I run 1 test ng runner class for tests that run headless and 1 test ng runner class for tests that run not headless (for specific tests that don't run under headless mode clipboard data validating etc)

**Comment by prashant-ramcharan** [comment]
@Vishnuvenu89 I can add a `slackTestIdentifier` Courgette option in a future release.

With regards to sending a link to slack for allure / extent reports - this link would just be pointing to a local path from the machine executing the tests. As these reports are not published anywhere with a public URL, it doesn't make sense to add a link to slack because no one would be able to open it.

**Comment by prashant-ramcharan** [comment]
@mateiQA In short, this cannot be done.

`sessionId` is immutable by design and Courgette cannot aggregate and merge results from 2 separate Java processes (_i.e. Courgette runners_). Results are calculated in memory within each Courgette process so even if we use the same `sessionId` for multiple Courgette runners, it wouldn't help merge results because one process wouldn't know the results of the other.

**Comment by mateiQA** [comment]
> @mateiQA In short, this cannot be done.
> 
> `sessionId` is immutable by design and Courgette cannot aggregate and merge results from 2 separate Java processes (_i.e. Courgette runners_). Results are calculated in memory within each Courgette process so even if we use the same `sessionId` for multiple Courgette runners, it wouldn't help merge results because one process wouldn't know the results of the other.

thanks for the information

**Comment by prashant-ramcharan** [comment]
You can now use Courgette option `slackTestId` to specify a custom test id.

**Comment by Vishnuvenu89** [comment]
Great, i will check this today!!!
