### ISSUE TITLE
Multithreading taking longer time

### ISSUE THREAD

**Issue by arihan** [prashant-ramcharan/courgette-jvm#319]
When we use the `cucumber.api.cli.Main` for a multithread run then the thread finish the scenario picks the next scenario immediately. However while using this library then say starting with parallel run with thread count -10 then until all the threads finished the next set of 10 scenarios don't start.
As example :- at the beginning 10 threads started 10 scenarios. Once all the threads finished their respective scenario then next set of 10 scenarios would start .

We observed it's almost made the execution time to double. Is there any plan to handle this ?

**Comment by prashant-ramcharan** [comment]
**Please provide a project to fully demonstrate this issue.** 

I'm unable to _handle_ anything without knowing the full issue.

* Are you using a JVM profiler to measure timings?

**Comment by prashant-ramcharan** [comment]
Some further info on how Courgette works:

Courgette uses a queuing system and creates a queue of tests based on the number of threads (_or an optimised thread count that Courgette determines at runtime_)

Courgette then dequeues tests in batches and waits for all tests in each batch to complete before the next batch can start. This is the way this library is designed to work.

I've not had anyone report any issues where Courgette runs in double the time so if you can provide a project to demonstrate double timings, that would be great!

Also worth mentioning, Courgette does additional processing at the end of each test run for merging multiple reports into a consolidated report and depending on the Courgette plugins you use this could slightly increase the timings due to additional post test execution processing.

**Comment by mateiQA** [comment]
My comment might be totally unrelated but I was getting a lot of OutOfMemory issues after running a test suite using 4 threads after around 2 hours of running. This started occurring after a cucumber update. In my case, the gradle worker needed more memory as it was running out of memory when trying to store the test results and it was increasing the test run times _**by a lot**_

I've set the gradle worker processes for the test task to include the following, which fixed my issue. Give it a try and see if it makes any difference

```
test {
    // heap settings for the Gradle worker processes
    minHeapSize = '256m'
    maxHeapSize = '2048m' 
}
```

**Comment by prashant-ramcharan** [comment]
Closing inactive issue.
