### ISSUE TITLE
New threadDelay option

### ISSUE THREAD

**Issue by mateiQA** [prashant-ramcharan/courgette-jvm#361]
fixedThreadDelay: A fixed time in milliseconds that Courgette will pause before the start of each feature or scenario.

randomThreadDelay: A random time in milliseconds that Courgette will pause before the start of each feature or scenario. Courgette will automatically set a random time between 0 and this value.

Hello @prashant-ramcharan, can you please explain why this would be used for? I am very curious and I am trying to think of a use case for this

**Comment by prashant-ramcharan** [comment]
Hi @mateiQA 

There are a number of use cases for this but a few examples would be:

-  If you have 2 tests that run in parallel and both tests require access to a shared resource (i.e. database, file etc), both tests would try to acquire a lock on the resource if they start at the same time, having a `randomThreadDelay` would allow for `test 1` to start ahead of `test 2` (_or vice versa_) so that `test 1` can acquire the lock, run the test and release the lock whilst `test 2` waits to acquire the lock. 

- If the application under test is still processing (i.e data, files, state etc) after a test completes, you could use the `fixedThreadDelay` to allow a grace period before the start of each test. This would also be useful if your tests uses an `external service` to perform additional tasks (_not test specific_) after a test completes without explicitly adding `wait times (Thread.sleep)` within a test.
