### ISSUE TITLE
Report not generated due to com.google.gson.stream.MalformedJsonException

### ISSUE THREAD

**Issue by divanov-ki** [prashant-ramcharan/courgette-jvm#422]
@prashant-ramcharan I bumped courgette-jvm from `6.13.0` to  `6.17.0` (and subsequently to `6.18.0` to see if behaviour is different) and the reporting broke with the following exception thrown:

![Screenshot 2024-11-19 at 13 59 49](https://github.com/user-attachments/assets/b03e9859-2f6c-41eb-8e67-3ad3bdbd74ee)

For context our test run includes 300+ scenarios executed, so quite a bit of test related metadata generated to support the report generation at the end of execution. Could this be related to the bugfix you added in `6.17.0` to resolve the creation of parent directories for reporting issue?

**Comment by divanov-ki** [comment]
Worth noting that more conservative runs with less scenario executed generate the report just fine

**Comment by divanov-ki** [comment]
I realise this issue is actually a duplicate of https://github.com/prashant-ramcharan/courgette-jvm/issues/410. You can treat it as a confirmation the it's still an issue for extended test runs

**Comment by prashant-ramcharan** [comment]
Hi, I'm not sure if it's related to https://github.com/prashant-ramcharan/courgette-jvm/issues/410 as in this case the report generation was attempted whereas in issue 410 the report generation failed completely, likely related to JVM out of memory.

The issue here seems to be the parsing of the json file.

You should see a `courgette-report-processing-errors.txt` if the are any processing errors.

1. Could you share the json report for me to debug?
2. Can you consistently reproducible this?
3. Is it the exact same error every time?
4. Do you have the `json` plugin in your runner (i.e. `Courgette runner -> cucumberOptions -> plugin -> json:some-path`) enabled? Have you tried disabling to test?

**Comment by divanov-ki** [comment]
Prashant, thanks for the response. This was spotted via GHA runs, but you've given me some leads to chase. I'll let you know how I get on.
